apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-topic-registry
  namespace: confluent
data:
  topics: |
    - name: topic-a
      partitionCount: 12
      replicas: 1
      configs:
        cleanup.policy: "compact"
      kafkaCluster: kafka