apiVersion: cfk.homelab.dev/v1alpha1
kind: KafkaTopicRegistry
metadata:
  name: default
spec:
  topics:
    - name: topic-a
      partitionCount: 12
      replicas: 1
      kafkaCluster: kafka
      configs:
        cleanup.policy: "compact"