apiVersion: cfk.homelab.dev/v1alpha1
kind: KafkaTopicRequest
metadata:
  name: default
spec:
  partitionCount: 12
  topics:
    - name: topic-a
      replicas: 1
      kafkaCluster: kafka
      configs:
        cleanup.policy: "compact"